version: 2

updates:
  - package-ecosystem: "cargo"
    directory: "/"
    commit-message:
      prefix: "[chore(workspace)]"
      include: "scope"
    target-branch: "main"
    schedule:
      interval: "weekly"

  - package-ecosystem: "cargo"
    directory: "/homestar-core"
    commit-message:
      prefix: "[chore(core)]"
      include: "scope"
    target-branch: "main"
    schedule:
      interval: "weekly"

  - package-ecosystem: "cargo"
    directory: "/homestar-runtime"
    commit-message:
      prefix: "[chore(runtime)]"
      include: "scope"
    target-branch: "main"
    schedule:
      interval: "weekly"

  - package-ecosystem: "cargo"
    directory: "/homestar-guest-wasm"
    commit-message:
      prefix: "[chore(guest-wasm)]"
      include: "scope"
    target-branch: "main"
    schedule:
      interval: "weekly"

  - package-ecosystem: "cargo"
    directory: "/homestar-wasm"
    commit-message:
      prefix: "[chore(wasm)]"
      include: "scope"
    target-branch: "main"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/docker"
    commit-message:
      prefix: "[chore(docker)]"
      include: "scope"
    target-branch: "main"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    commit-message:
      prefix: "[chore(ci)]"
      include: "scope"
    target-branch: "main"
    schedule:
      interval: "weekly"
