version: 2

updates:
  - package-ecosystem: "cargo"
    directory: "/"
    commit-message:
      prefix: "[chore(cargo)]"
      include: "scope"
    target-branch: "main"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  - package-ecosystem: "docker"
    directory: "/docker"
    commit-message:
      prefix: "[chore(docker)]"
      include: "scope"
    target-branch: "main"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    commit-message:
      prefix: "[chore(ci)]"
      include: "scope"
    target-branch: "main"
    schedule:
      interval: "weekly"
