# See https://pre-commit.com for more information
# pre-commit install
# pre-commit install --hook-type commit-msg
exclude: ^(LICENSE|LICENSE*)
repos:
  - repo: local
    hooks:
      - id: fmt
        name: fmt
        description: Format rust files.
        entry: cargo fmt
        language: system
        types: [rust]
        args: ["--all", "--", "--check"]
      - id: cargo-check
        name: cargo check
        description: Check the package for errors.
        entry: cargo check --workspace
        language: system
        types: [rust]
        pass_filenames: false
      - id: clippy
        name: clippy
        description: Lint via clippy
        entry: cargo clippy
        language: system
        args: ["--workspace", "--", "-D", "warnings"]
        types: [rust]
        pass_filenames: false
      - id: docs
        name: docs
        description: Check docs for warnings.
        entry: env RUSTDOCFLAGS=-Dwarnings cargo doc
        language: system
        args: ["--workspace", "--document-private-items"]
        types: [rust]
        pass_filenames: false

  - repo: https://github.com/kamadorueda/alejandra
    rev: bb7f2ad3f176aa8e9e2944a10061f7989c8fef17  # frozen: 1.3.0
    hooks:
      - id: alejandra
        files: \.nix$

  - repo: https://github.com/DevinR528/cargo-sort
    rev: v1.0.9
    hooks:
      - id: cargo-sort
        args: ["-w"]

  - repo: https://github.com/ComPWA/mirrors-taplo
    rev: v0.8.1
    hooks:
      - id: taplo
        args: ["fmt"]
        types:
          - toml

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v2.1.1
    hooks:
      - id: conventional-pre-commit
        stages:
          - commit-msg

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: no-commit-to-branch
        args: ["-b", "main"]
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: \.txt$
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
        args: ['--maxkb=4000']
      - id: detect-private-key
        exclude: __testkey
      - id: check-executables-have-shebangs
      - id: check-toml
