ignore:
  - "*/tests/*"
  - "*/src/test_utils/*"

comment:
  layout: "reach, diff, flags, files"
  require_changes: true

github_checks:
  annotations: false

coverage:
  status:
    project:
      default:
        threshold: 5%
    patch:
      default:
        target: 0%
        if_ci_failed: ignore
