ignore:
  - "homestar/tests"
  - "homestar/src/test_utils"
  - "homestar-guest-wasm"
  - "homestar-wasm/src/test_utils"

comment:
  layout: "reach, diff, flags, files"
  require_changes: true

github_checks:
  annotations: false

coverage:
  status:
    project:
      default:
        threshold: 5%
