[build.env]
passthrough = [
  "CARGO_INCREMENTAL",
  "RUST_BACKTRACE",
  "CARGO_TERM_COLOR",
  "RUSTFLAGS",
]

# When running `cross` with nix, do this within `nix-shell -p gcc rustup`.
#
# Then, run
#
# `cross build -p homestar-runtime --target x86_64-unknown-linux-musl`
# or
# `cross build -p homestar-runtime --target aarch64-unknown-linux-musl`

[target.x86_64-unknown-linux-musl]
image = "burntsushi/cross:x86_64-unknown-linux-musl"

[target.aarch64-unknown-linux-musl]
image = "burntsushi/cross:aarch64-unknown-linux-musl"

[target.x86_64-apple-darwin]
image = "freeznet/x86_64-apple-darwin-cross:11.3"

[target.aarch64-apple-darwin]
image = "freeznet/aarch64-apple-darwin-cross:11.3"
