# For documentation on how to configure this file,
# see https://diesel.rs/guides/configuring-diesel-cli

[print_schema]
file = "homestar-runtime/src/db/schema.rs"

[migrations_directory]
dir = "homestar-runtime/migrations"
