[workspace]
changelog_update = false
publish = false
pr_labels = ["release"]

[[package]]
name = "homestar-core"
publish = true
changelog_update = true

[[package]]
name = "homestar-runtime"
publish = true
changelog_update = true

[[package]]
name = "homestar-wasm"
publish = true
changelog_update = true

[[package]]
name = "homestar-functions-add"
publish = false
changelog_update = false

[[package]]
name = "homestar-functions-test"
publish = false
changelog_update = false

[[package]]
name = "example-websocket-relay"
publish = false
changelog_update = false
