[workspace]
pr_labels = ["release"]

[[package]]
name = "homestar-invocation"
publish = true
changelog_update = true

[[package]]
name = "homestar-runtime"
publish = true
changelog_update = true

[[package]]
name = "homestar-wasm"
publish = true
changelog_update = true

[[package]]
name = "homestar-workflow"
publish = true
changelog_update = true
