[toolchain]
channel = "stable"

extensions = [
  "cargo",
  "clippy",
  "llvm-tools-preview",
  "rustfmt",
  "rust-src",
  "rust-std",
]

targets = [
  "wasm32-unknown-unknown",
  "wasm32-wasi",
  "x86_64-apple-darwin",
  "aarch64-apple-darwin",
  "x86_64-unknown-linux-gnu",
  "x86_64-unknown-linux-musl",
  "aarch64-unknown-linux-musl",
]
