[node]
[node.network.keypair_config]
existing = { key_type = "ed25519", path = "./__testkey_ed25519.pem" }

[node.network.metrics]
port = 4021

[node.network.rpc]
port = 9821

[node.network.webserver]
host = "127.0.0.1"
port = 8021

[node.network.ipfs]
host = "127.0.0.1"
port = 5001
