[node]

[node.network.libp2p]
listen_address = "/ip4/0.0.0.0/tcp/7001"

[node.network.libp2p.rendezvous]
enable_server = true

[node.network.metrics]
port = 4000

[node.network.rpc]
port = 3030

[node.network.webserver]
port = 1337
