[package]
name = "homestar-runtime"
version = "0.1.0"
description = "Homestar CLI"
keywords = ["ipfs", "workflows", "ipld", "ipvm"]
categories = ["workflow-engines", "distributed-systems", "runtimes", "networking"]
include = ["/src", "README.md", "LICENSE"]
license = { workspace = true }
readme = "README.md"
edition = { workspace = true }
rust-version = { workspace = true }
documentation = "https://docs.rs/homestar"
repository = "https://github.com/ipvm-wg/homestar"
authors = { workspace = true }

[lib]
path = "src/lib.rs"
bench = false
doctest = true
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "homestar-runtime"
path = "src/main.rs"
doc = false
bench = false

[dependencies]
# return to version.workspace = true after the following issue is fixed:
# https://github.com/DevinR528/cargo-sort/issues/47
anyhow = { workspace = true }
async-trait = "0.1"
axum = { version = "0.6", features = ["ws", "headers"], optional = true }
bincode = { version = "2.0.0-rc.3", features = ["serde"] }
byte-unit = { workspace = true }
clap = { version = "4.3", features = ["derive", "color", "help", "env"] }
concat-in-place = "1.1"
config = "0.13"
console-subscriber = { version = "0.1", default-features = false, features = [ "parking_lot" ], optional = true }
crossbeam = "0.8"
daemonize = "0.5"
dagga = "0.2"
dashmap = "5.5"
diesel = { version = "2.1", features = ["sqlite", "r2d2", "returning_clauses_for_sqlite_3_35"] }
diesel_migrations = "2.1"
dotenvy = "0.15"
enum-assoc = { workspace = true }
evmap = "10.0"
fnv = "1.0"
futures = { workspace = true }
headers = "0.3"
homestar-core = { version = "0.1", path = "../homestar-core" }
homestar-wasm = { version = "0.1", path = "../homestar-wasm" }
http = "0.2"
http-serde = "1.1"
indexmap = "2.0"
ipfs-api = { version = "0.17", optional = true }
ipfs-api-backend-hyper = { version = "0.6", features = ["with-builder", "with-send-sync"], optional = true }
libipld = { workspace = true }
libp2p = { version = "0.52", default-features = false, features = ["kad", "request-response", "macros",
    "identify", "ed25519", "secp256k1", "mdns", "gossipsub", "request-response", "tokio", "dns", "tcp",
    "noise", "cbor", "yamux", "websocket"] }
libsqlite3-sys = { version = "0.26", features = ["bundled"] }
miette = { version = "5.10", features = ["fancy"] }
openssl = { version = "0.10", features = ["vendored"] }
proptest = { version = "1.2", optional = true }
rand = "0.8"
reqwest = { version = "0.11", features = ["json"] }
sec1 = { version = "0.7", features = ["pem", "der"] }
semver = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_ipld_dagcbor = { workspace = true }
serde_with = { version = "3.1", features = ["base64"] }
stream-cancel = "0.8"
strum = { version = "0.25", features = ["derive"] }
tabled = { git = "https://github.com/zhiburt/tabled.git" }
tarpc = { version = "0.33", features = ["serde-transport", "serde-transport-bincode", "tcp"] }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-util = { version = "0.7", features = ["time"] }
tracing = { workspace = true }
tracing-appender = "0.2"
tracing-logfmt = "0.3"
tracing-subscriber = { version = "0.3", features = ["env-filter", "parking_lot", "registry"] }
tryhard = "0.5"
url = "2.4"

[target.'cfg(not(windows))'.dependencies]
daemonize = "0.5"

[dev-dependencies]
assert_cmd = "2.0"
criterion = "0.5"
homestar-core = { version = "0.1", path = "../homestar-core", features = [ "test_utils" ] }
json = "0.12"
nix = "0.26"
once_cell = "1.18"
predicates = "3.0"
rand = { workspace = true }
retry = "2.0"
serial_test = "2.0"
sysinfo = "0.29"
tokio-tungstenite = "0.20"
wait-timeout = "0.2"

[features]
default = ["ipfs", "websocket-server"]
console = ["dep:console-subscriber"]
ipfs = ["dep:ipfs-api", "dep:ipfs-api-backend-hyper"]
test_utils = ["dep:proptest"]
websocket-server = ["dep:axum"]

[package.metadata.docs.rs]
all-features = true
# defines the configuration attribute `docsrs`
rustdoc-args = ["--cfg", "docsrs"]
