[package]
name = "homestar-runtime"
version = "0.1.0"
description = "Homestar CLI"
keywords = ["ipfs", "workflows", "ipld", "ipvm"]
categories = ["workflow-engines", "distributed-systems", "runtimes", "networking"]
include = ["/src", "README.md", "LICENSE"]
license = { workspace = true }
readme = "README.md"
edition = { workspace = true }
rust-version = { workspace = true }
documentation = "https://docs.rs/homestar"
repository = "https://github.com/ipvm-wg/homestar"
authors = { workspace = true }

[lib]
path = "src/lib.rs"
bench = false
doctest = true
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "homestar-runtime"
path = "src/main.rs"
doc = false
bench = false

[dependencies]
ansi_term = { version = "0.12", optional = true, default-features = false }
# return to version.workspace = true after the following issue is fixed:
# https://github.com/DevinR528/cargo-sort/issues/47
anyhow = { workspace = true }
async-trait = "0.1"
axum = { version = "0.6", features = ["ws", "headers"] }
byte-unit = { version = "4.0", default-features = false }
clap = { version = "4.1", features = ["derive", "color", "help"] }
concat-in-place = "1.1"
config = "0.13"
console-subscriber = { version = "0.1", default-features = false, features = [ "parking_lot" ], optional = true }
crossbeam = "0.8"
dagga = "0.2"
diesel = { version = "2.1", features = ["sqlite", "r2d2", "returning_clauses_for_sqlite_3_35"] }
dotenvy = "0.15"
enum-assoc = "0.4"
futures = "0.3"
headers = "0.3"
homestar-core = { version = "0.1", path = "../homestar-core" }
homestar-wasm = { version = "0.1", path = "../homestar-wasm" }
http = "0.2"
http-serde = "1.1"
indexmap = "1.9"
ipfs-api = { version = "0.17", optional = true }
ipfs-api-backend-hyper = { version = "0.6", features = ["with-builder", "with-send-sync"], optional = true }
itertools = "0.10"
libipld = "0.16"
libp2p = { version = "0.51", features = ["kad", "request-response", "macros", "identify", "mdns", "gossipsub", "tokio", "dns", "mplex", "tcp", "noise", "yamux", "websocket"] }
libp2p-identity = "0.1"
libsqlite3-sys = { version = "0.26", features = ["bundled"] }
openssl = { version = "0.10", features = ["vendored"] }
proptest = { version = "1.1", optional = true }
reqwest = { version = "0.11", features = ["json"] }
semver = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_with = "2.3"
thiserror = "1.0"
tokio = { workspace = true }
tracing = { workspace = true }
tracing-logfmt = { version = "0.3", optional = true }
tracing-subscriber = { version = "0.3", features = ["env-filter", "parking_lot", "registry"] }
tryhard = "0.5"
url = "2.3"

[dev-dependencies]
criterion = "0.4"
diesel_migrations = "2.1"
homestar-core = { version = "0.1", path = "../homestar-core", features = [ "test_utils" ] }
json = "0.12"
tokio-tungstenite = "0.18"

[features]
default = ["console", "ipfs", "logfmt"]
ansi-logs = ["ansi_term"]
console = ["console-subscriber"]
ipfs = ["ipfs-api", "ipfs-api-backend-hyper"]
logfmt = ["tracing-logfmt"]
test_utils = ["proptest"]

[package.metadata.docs.rs]
all-features = true
# defines the configuration attribute `docsrs`
rustdoc-args = ["--cfg", "docsrs"]
