[package]
name = "homestar-runtime-tests-proc-macro"
version = "0.0.0"
publish = false
edition = { workspace = true }
rust-version = { workspace = true }

[lib]
proc_macro = true
doc = false

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = "2.0"
