[package]
name = "homestar-guest-wasm"
publish = false
version = "0.1.0"
edition = { workspace = true }

[dependencies]
image = { version = "0.24" }
wit-bindgen = "0.4"

[lib]
crate-type = ["cdylib", "rlib"]
