[package]
name = "homestar-guest-wasm"
publish = false
version = "0.1.0"
edition = { workspace = true }

[dependencies]
wit-bindgen = { git = "https://github.com/bytecodealliance/wit-bindgen", branch = "main" }

[lib]
crate-type = ["cdylib", "rlib"]
