[package]
name = "homestar-wasm"
version = "0.1.0"
description = ""
keywords = []
categories = []

include = ["/src", "README.md", "LICENSE"]
license = "Apache"
readme = "README.md"
edition = { workspace = true }
rust-version = { workspace = true }
documentation = "https://docs.rs/homestar-wasm"
repository = "https://github.com/ipvm-wg/homestar"
authors = { workspace = true }

[lib]
path = "src/lib.rs"
bench = false
doctest = true
crate-type = ["cdylib", "rlib"]

[dependencies]
anyhow = "1.0"
atomic_refcell = "0.1"
heck = "0.4"
itertools = "0.10"
libipld = "0.16"
libipld-core = { version = "0.16", features = ["serde-codec", "serde"] }
rust_decimal = "1.28"
serde_ipld_dagcbor = "0.2"
stacker = "0.1"
thiserror = "1.0"
tracing = "0.1"
wasi-cap-std-sync = { git = "https://github.com/bytecodealliance/preview2-prototyping" }
wasi-common = { git = "https://github.com/bytecodealliance/preview2-prototyping" }
wasmparser = "0.101"
wasmtime = { git = "https://github.com/bytecodealliance/wasmtime", features = ["async", "component-model", "default"] }
wasmtime-component-util = { git = "https://github.com/bytecodealliance/wasmtime" }
wat = "1.0"
wit-component = "0.7"

[dev-dependencies]
criterion = "0.4"
tokio = { version = "1.25", default_features = false }
tokio-test = "0.4"

[features]
default = []
