[package]
name = "homestar-wasm"
version = "0.1.0"
description = "Homestar Wasm / Wasmtime implementation and IPLD <=> WIT interpreter"
keywords = ["wasm", "wasmtime", "wit", "ipld", "ipvm"]
categories = ["wasm", "execution-engines"]
include = ["/src", "README.md", "LICENSE"]
license = { workspace = true }
readme = "README.md"
edition = { workspace = true }
rust-version = { workspace = true }
documentation = "https://docs.rs/homestar-wasm"
repository = "https://github.com/ipvm-wg/homestar"
authors = { workspace = true }

[lib]
path = "src/lib.rs"
bench = false
doctest = true

[dependencies]
# return to version.workspace = true after the following issue is fixed:
# https://github.com/DevinR528/cargo-sort/issues/47
anyhow = { workspace = true }
atomic_refcell = "0.1"
enum-as-inner = { workspace = true }
heck = "0.4"
homestar-core = { version = "0.1", path = "../homestar-core" }
itertools = "0.10"
libipld = "0.16"
libipld-core = { version = "0.16", features = ["serde-codec", "serde"] }
rust_decimal = "1.30"
stacker = "0.1"
thiserror = { workspace = true }
tracing = { workspace = true }
wasi-common = "8.0"
wasmparser = "0.104"
wasmtime = { version = "8.0", features = ["async", "component-model", "default"] }
wasmtime-component-util = "8.0"
wat = "1.0"
wit-component = "0.8"

[dev-dependencies]
criterion = "0.5"
image = "0.24"
serde_ipld_dagcbor = "0.3"
tokio = { workspace = true }

[features]
default = []

[package.metadata.docs.rs]
all-features = true
# defines the configuration attribute `docsrs`
rustdoc-args = ["--cfg", "docsrs"]
