[profile.default]
retries = 0
test-threads = "num-cpus"
threads-required = 1
slow-timeout = { period = "60s", terminate-after = 1 }

[profile.ci]
retries = { backoff = "exponential", count = 4, delay = "30s", jitter = true, max-delay = "300s" }
failure-output = "immediate-final"
leak-timeout = "800ms"
slow-timeout = { period = "100s", terminate-after = 2 }
fail-fast = false

[test-groups]
serial = { max-threads = 1 }
integration = { max-threads = "num-cpus" }

[[profile.default.overrides]]
filter = 'test(/_serial$/)'
test-group = 'serial'

[[profile.default.overrides]]
filter = 'test(/_integration$/)'
threads-required = 4
test-group = 'integration'

[[profile.ci.overrides]]
filter = 'test(/_serial$/)'
test-group = 'serial'

[[profile.ci.overrides]]
filter = 'test(/_integration$/)'
threads-required = 4
test-group = 'integration'
