[profile.default]
retries = 0
test-threads = "num-cpus"
threads-required = 1

[profile.ci]
retries = { backoff = "exponential", count = 3, delay = "30s", jitter = true, max-delay = "300s" }
failure-output = "immediate-final"
leak-timeout = "800ms"
slow-timeout = { period = "120s", terminate-after = 2 }
fail-fast = false

[test-groups]
serial = { max-threads = 4 }

[[profile.default.overrides]]
filter = 'test(/_serial$/)'
test-group = 'serial'
threads-required = 4

[[profile.ci.overrides]]
filter = 'test(/_serial$/)'
test-group = 'serial'
threads-required = 4
